# Generated by Django 5.1.15 on 2026-03-31 06:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('coordinator', 'Coordinator'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('response_snapshot', models.TextField(blank=True)),
                ('llm_calls_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('topic', models.TextField(help_text='Primary topic / research question')),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('technical_report', 'Technical Report'), ('news_article', 'News Article'), ('tutorial', 'Tutorial')], default='blog_post', max_length=30)),
                ('target_length', models.PositiveIntegerField(default=1500, help_text='Target word count')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('additional_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('llm_calls_count', models.PositiveIntegerField(default=0)),
                ('llm_tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('research_summary', 'Research Summary'), ('outline', 'Outline'), ('draft', 'Draft'), ('edited_draft', 'Edited Draft'), ('final_content', 'Final Content'), ('seo_metadata', 'SEO Metadata'), ('qa_report', 'QA Report'), ('fact_check_report', 'Fact Check Report')], max_length=30)),
                ('content_text', models.TextField(blank=True)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='jobs.agentrun')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='jobs.job'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveSmallIntegerField(default=1)),
                ('triggered_by', models.CharField(choices=[('coordinator', 'Coordinator'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], help_text='Agent that triggered this revision', max_length=30)),
                ('reason', models.TextField(help_text='Why the revision was needed')),
                ('issues', models.JSONField(default=list, help_text='List of specific issues to fix')),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'ordering': ['revision_number'],
            },
        ),
    ]
