# Generated by Django 5.1.15 on 2026-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_llm_provider_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('coordinator_router', 'Coordinator Router'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('section_writer', 'Section Writer'), ('join_draft', 'Join Draft'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='revision',
            name='triggered_by',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('coordinator_router', 'Coordinator Router'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('section_writer', 'Section Writer'), ('join_draft', 'Join Draft'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], help_text='Agent that triggered this revision', max_length=30),
        ),
    ]
