# Generated by Django 5.1.15 on 2026-05-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_agentrun_agent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quality_mode',
            field=models.CharField(choices=[('fast', 'Fast'), ('standard', 'Standard'), ('strict', 'Strict')], default='standard', help_text='Controls revision depth and fact-check strictness', max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('research_summary', 'Research Summary'), ('outline', 'Outline'), ('draft', 'Draft'), ('edited_draft', 'Edited Draft'), ('final_content', 'Final Content'), ('seo_metadata', 'SEO Metadata'), ('qa_report', 'QA Report'), ('fact_check_report', 'Fact Check Report'), ('source_documents', 'Source Documents')], max_length=30),
        ),
    ]
