# Generated by Django 5.1.15 on 2026-05-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_quality_mode_alter_artifact_artifact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='audience',
            field=models.CharField(blank=True, default='', help_text='Target audience, e.g. developers, executives, students', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('tech', 'Tech'), ('marketing', 'Marketing'), ('education', 'Education'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('legal', 'Legal')], default='tech', help_text='Domain guide used by research, writing, editing, and QA', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='tone',
            field=models.CharField(choices=[('clear', 'Clear'), ('professional', 'Professional'), ('practical', 'Practical'), ('executive', 'Executive'), ('friendly', 'Friendly'), ('formal', 'Formal')], default='clear', help_text='Preferred writing tone', max_length=30),
        ),
    ]
