# Generated by Django 5.1.15 on 2026-05-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_audience_job_domain_job_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='media_inputs',
            field=models.JSONField(blank=True, default=list, help_text='Uploaded media files or media URLs attached to the job'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('coordinator_router', 'Coordinator Router'), ('media_research', 'Media Research'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('section_writer', 'Section Writer'), ('join_draft', 'Join Draft'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('research_summary', 'Research Summary'), ('outline', 'Outline'), ('draft', 'Draft'), ('edited_draft', 'Edited Draft'), ('final_content', 'Final Content'), ('seo_metadata', 'SEO Metadata'), ('qa_report', 'QA Report'), ('fact_check_report', 'Fact Check Report'), ('source_documents', 'Source Documents'), ('media_inputs', 'Media Inputs'), ('media_transcripts', 'Media Transcripts'), ('media_captions', 'Media Captions')], max_length=30),
        ),
        migrations.AlterField(
            model_name='revision',
            name='triggered_by',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('coordinator_router', 'Coordinator Router'), ('media_research', 'Media Research'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('section_writer', 'Section Writer'), ('join_draft', 'Join Draft'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], help_text='Agent that triggered this revision', max_length=30),
        ),
    ]
