# Generated by Django 5.1.15 on 2026-05-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_media_inputs_alter_agentrun_agent_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='media_inputs',
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('coordinator_router', 'Coordinator Router'), ('image_research', 'Image Research'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('section_writer', 'Section Writer'), ('join_draft', 'Join Draft'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('research_summary', 'Research Summary'), ('outline', 'Outline'), ('draft', 'Draft'), ('edited_draft', 'Edited Draft'), ('final_content', 'Final Content'), ('seo_metadata', 'SEO Metadata'), ('qa_report', 'QA Report'), ('fact_check_report', 'Fact Check Report'), ('source_documents', 'Source Documents'), ('image_assets', 'Image Assets')], max_length=30),
        ),
        migrations.AlterField(
            model_name='revision',
            name='triggered_by',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('coordinator_router', 'Coordinator Router'), ('image_research', 'Image Research'), ('research', 'Research'), ('outline', 'Outline'), ('writer', 'Writer'), ('section_writer', 'Section Writer'), ('join_draft', 'Join Draft'), ('editor', 'Editor'), ('seo', 'SEO'), ('fact_checker', 'Fact Checker'), ('qa', 'QA')], help_text='Agent that triggered this revision', max_length=30),
        ),
    ]
