# Generated by Django 5.1.15 on 2026-05-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_media_inputs_alter_agentrun_agent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved_outline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='outline_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='outline_review_required',
            field=models.BooleanField(default=True, help_text='Pause after outline generation so the user can approve or edit it'),
        ),
        migrations.AddField(
            model_name='job',
            name='pipeline_state',
            field=models.JSONField(blank=True, default=dict, help_text='Latest resumable PipelineState checkpoint'),
        ),
    ]
