# Generated by Django 5.1.15 on 2026-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_approved_outline_job_outline_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('general', 'General'), ('food', 'Food & Lifestyle'), ('tech', 'Tech'), ('marketing', 'Marketing'), ('education', 'Education'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('legal', 'Legal')], default='general', help_text='Domain guide used by research, writing, editing, and QA', max_length=30),
        ),
    ]
